let bundles=[],selected=null,pollTimer=null;
async function load(){try{const r=await fetch('/api/catalog');const d=await r.json();bundles=d.bundles||[];window.till=d.till;document.getElementById('bundlesGrid').innerHTML=bundles.map((b,i)=>`<article class="bundle-card ${i===0?'featured':''}"><div class="bundle-icon">⌁</div><div class="bundle-top"><span class="bundle-name">${esc(b.name)}</span>${i===0?'<span class="popular">POPULAR</span>':''}</div><div class="price">KES ${Number(b.price).toFixed(0)}</div><div class="validity">${esc(b.validity||'Data bundle')} <span>•</span> ${esc(b.network)}</div><button class="btn btn-full" onclick="openBuy('${b.id}')">Choose bundle</button></article>`).join('')}catch(e){document.getElementById('bundlesGrid').innerHTML='<div class="notice error">Unable to load bundles. Please try again.</div>';}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function openBuy(id){selected=bundles.find(x=>x.id===id);if(!selected)return;document.getElementById('modalBundle').textContent=`${selected.name} • KES ${Number(selected.price).toFixed(0)}`;document.getElementById('modal').classList.add('show');document.getElementById('phone').focus();}
function closeModal(){clearInterval(pollTimer);document.getElementById('modal').classList.remove('show');document.getElementById('modalMsg').innerHTML='';document.getElementById('payBtn').disabled=false;document.getElementById('payBtn').textContent='Pay with M-PESA';}
async function startPayment(){const phone=document.getElementById('phone').value.trim();const msg=document.getElementById('modalMsg');const btn=document.getElementById('payBtn');if(!/^0?(7|1)\d{8}$|^254(7|1)\d{8}$/.test(phone.replace(/\s/g,''))){msg.innerHTML='<div class="notice error">Enter a valid Kenyan mobile number.</div>';return;}btn.disabled=true;btn.textContent='Creating secure order…';try{const r=await fetch('/api/orders/intents',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({bundleId:selected.id,phone})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not create order');document.getElementById('ref').value=d.orderReference;btn.textContent=`Request M-PESA prompt — KES ${d.amount}`;const p=await fetch('/api/payments/stkpush',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({orderReference:d.orderReference})});const pd=await p.json();if(!p.ok)throw new Error(pd.error||'M-PESA prompt could not be started');document.getElementById('modalBundle').innerHTML=`<b>${esc(d.bundleName)}</b> • KES ${Number(d.amount).toFixed(0)}<br><span class="muted">Order ${esc(d.orderReference)}</span>`;msg.innerHTML='<div class="notice success"><b>Check your phone now.</b><br>A secure M-PESA prompt has been sent. Enter your M-PESA PIN on the M-PESA prompt on your phone. Do not enter it here.</div>';btn.textContent='Waiting for payment…';pollOrder(d.orderReference);}catch(e){msg.innerHTML=`<div class="notice error">${esc(e.message)}</div>`;btn.disabled=false;btn.textContent='Pay with M-PESA';}}
function pollOrder(ref){clearInterval(pollTimer);let tries=0;pollTimer=setInterval(async()=>{tries++;try{const r=await fetch('/api/orders/'+encodeURIComponent(ref));const d=await r.json();if(!r.ok)return;if(d.payment_status==='SUCCESS'){clearInterval(pollTimer);document.getElementById('modalMsg').innerHTML='<div class="notice success"><b>Payment confirmed.</b><br>Your bundle is now being processed.</div>';setTimeout(closeModal,2200);checkOrder();}else if(d.payment_status==='FAILED'){clearInterval(pollTimer);document.getElementById('modalMsg').innerHTML='<div class="notice error">M-PESA payment was not completed. You can close this window and try again.</div>';document.getElementById('payBtn').disabled=false;document.getElementById('payBtn').textContent='Try again';}if(tries>=60)clearInterval(pollTimer);}catch{}} ,3000);}
async function checkOrder(){const ref=document.getElementById('ref').value.trim();if(!ref)return;const r=await fetch('/api/orders/'+encodeURIComponent(ref));const d=await r.json();document.getElementById('orderStatus').innerHTML=r.ok?`<div class="notice ${d.delivery_status==='DELIVERED'?'success':''}"><b>${esc(d.bundle_name||'Bundle')}</b><br>Order: ${esc(d.order_reference)}<br>Payment: <span class="pill">${esc(d.payment_status)}</span> &nbsp; Delivery: <span class="pill">${esc(d.delivery_status)}</span>${d.failure_reason?`<br>Reason: ${esc(d.failure_reason)}`:''}</div>`:`<div class="notice error">${esc(d.error)}</div>`;}
load();
